[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.69"
reqwest = { version = "0.12.5", features = ["json"] }
serde_json = "1.0.120"
wasm-bindgen-futures = "0.4.42"
web-sys = "0.3.69"
yew = { version = "0.21.0", features = ["csr"] }
yew-router = "0.18.0"
